#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

PGSQL_HOME="${PGSQL_HOME:-/var/lib/postgresql}";
PGSQL_BACKUPDIR="${PGSQL_BACKUPDIR:-${PGSQL_HOME}/backups}"; # only created during initializing, not after
PGDATA="${PGDATA:-${PGSQL_HOME}/data}"; # only created during initializing, not after

vecho "Ensure configuration directories exist.";
mkdir -p \
    "${PGDATA}" \
    "${PGSQL_BACKUPDIR}" \
    /var/run/postgresql \
    ;

# fix permissions
if [ -z "${PGSQL_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    find \
        "${PGDATA}" \
        "${PGSQL_BACKUPDIR}" \
        /var/run/postgresql \
        \
        \! -user ${S6_USER:-postgres} -exec \
        chown --no-dereference \
        ${S6_USER:-postgres}:${PGID:-1000} \
        '{}' +;

    # postgres nags if not set
    chmod 700 \
        "${PGDATA}" \
        "${PGSQL_BACKUPDIR}" \
        ;
fi;
